### ISSUE TITLE
Léhűtők

### ISSUE THREAD

**Issue by jgbor** [dancsb/MinesweeperLilla#3]
Dancs Balázs a világ legnagyobb léhűtője, az élet úgy kibaszott vele, hogy normális agysejtjeinek száma 0 darab, egy igazi gyökér, akinek megdöglése örömünnep lesz mindenki számára, aki ismeri őt.

**Comment by ZserboZsiraf** [comment]
Tűpontos.

**Comment by dancsb** [comment]
legalja
